CREATE TABLE TASK (ID INTEGER NOT NULL, DATE DATE, DEPARTMENT VARCHAR(255), DESCRIPTION VARCHAR(255), finish_time TIME, follow_up_action VARCHAR(255), NOTE VARCHAR(255), OUTCOME VARCHAR(255), start_time TIME, under_plan BOOLEAN, VERSION INTEGER NOT NULL, user_id INTEGER, PRIMARY KEY (ID))
CREATE TABLE UNIT_OF_COMPETENCY (ID INTEGER NOT NULL, CODE VARCHAR(10) NOT NULL, UNIT_SECTOR VARCHAR(255) NOT NULL, VERSION INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE public.USER (ID INTEGER NOT NULL, EMAIL VARCHAR(255), PASSWORD VARCHAR(255), VERSION INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE campus (ID INTEGER NOT NULL UNIQUE, NUMBER VARCHAR(10) NOT NULL, POSTCODE VARCHAR(4) NOT NULL, STREET VARCHAR(100) NOT NULL, VERSION INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE room (ID INTEGER NOT NULL UNIQUE, COMMENT VARCHAR(100), NUMBER VARCHAR(5), VERSION INTEGER NOT NULL, campus_id INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE PERSON (ID INTEGER NOT NULL, FIRSTNAME VARCHAR(50) NOT NULL, LASTNAME VARCHAR(50) NOT NULL, VERSION INTEGER NOT NULL, PRIMARY KEY (ID))
ALTER TABLE TASK ADD CONSTRAINT FK_TASK_user_id FOREIGN KEY (user_id) REFERENCES public.USER (ID)
ALTER TABLE room ADD CONSTRAINT FK_room_campus_id FOREIGN KEY (campus_id) REFERENCES campus (ID)
CREATE SEQUENCE PERSON_ID_GENERATOR START WITH 1
CREATE SEQUENCE CAMPUS_ID_GENERATOR START WITH 1
CREATE SEQUENCE UNIT_OF_COMPETENCY_ID_GENERATOR START WITH 1
CREATE SEQUENCE TASK_SEQ START WITH 1
CREATE SEQUENCE USER_SEQ START WITH 1
CREATE SEQUENCE ROOM_ID_GENERATOR START WITH 1
