CREATE TABLE TASK (ID INTEGER NOT NULL, DATE DATE, DEPARTMENT VARCHAR(255), DESCRIPTION VARCHAR(255), finish_time TIME, follow_up_action VARCHAR(255), NOTE VARCHAR(255), OUTCOME VARCHAR(255), start_time TIME, under_plan BOOLEAN, user_id INTEGER, PRIMARY KEY (ID))
CREATE TABLE UNIT_OF_COMPETENCY (ID INTEGER NOT NULL, CODE VARCHAR(10) NOT NULL, UNITSECTOR VARCHAR(255) NOT NULL, VERSAO INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE USER (ID INTEGER NOT NULL, EMAIL VARCHAR(255), PASSWORD VARCHAR(255), PRIMARY KEY (ID))
ALTER TABLE TASK ADD CONSTRAINT FK_TASK_user_id FOREIGN KEY (user_id) REFERENCES USER (ID)
CREATE SEQUENCE USER_ID_GENERATOR START WITH 1
CREATE SEQUENCE TASK_ID_GENERATOR START WITH 1
CREATE SEQUENCE UNIT_OF_COMPETENCY_ID_GENERATOR START WITH 1
