ALTER TABLE TASK DROP CONSTRAINT FK_TASK_user_id
DROP TABLE TASK CASCADE
DROP TABLE UNIT_OF_COMPETENCY CASCADE
DROP TABLE USER CASCADE
DROP SEQUENCE USER_ID_GENERATOR
DROP SEQUENCE TASK_ID_GENERATOR
DROP SEQUENCE UNIT_OF_COMPETENCY_ID_GENERATOR
