ALTER TABLE TASK DROP CONSTRAINT FK_TASK_user_id
ALTER TABLE room DROP CONSTRAINT FK_room_campus_id
DROP TABLE TASK CASCADE
DROP TABLE UNIT_OF_COMPETENCY CASCADE
DROP TABLE public.USER CASCADE
DROP TABLE campus CASCADE
DROP TABLE room CASCADE
DROP TABLE PERSON CASCADE
DROP SEQUENCE PERSON_ID_GENERATOR
DROP SEQUENCE CAMPUS_ID_GENERATOR
DROP SEQUENCE UNIT_OF_COMPETENCY_ID_GENERATOR
DROP SEQUENCE TASK_SEQ
DROP SEQUENCE USER_SEQ
DROP SEQUENCE ROOM_ID_GENERATOR
